name: Build Paperbits Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Zip dist folder
      run: |
        mkdir output
        zip -r output/dist.zip dist

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: paperbits-dist
        path: output/dist.zip
